In [ ]:
import os
if 'COLAB_GPU' in os.environ: # a hacky way of determining if you are in colab.
  print("Notebook is running in colab")
  from google.colab import drive
  drive.mount("/content/drive")
  DATA_DIR = "./drive/MyDrive/Data/"
  
else:
  # Find out what system we are using
  PLATFORM_SYSTEM = platform.system()

  # Check if we are in Darwin (macOS)
  if PLATFORM_SYSTEM == "Darwin":
      EXECUTABLE_PATH = Path("../dependencies/chromedriver")
  elif PLATFORM_SYSTEM == "Windows":
      EXECUTABLE_PATH = Path("../dependencies/chromedriver.exe")
  else:
      logging.critical("Chromedriver not found or Chromedriver is outdated...")
      exit()
  DATA_DIR = "../Data/raw/"

Notebook is running in colab
Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_excel("drive/MyDrive/Copy_of_hauer_county_NH_pop_SSPs.xlsx") #importing SEDAC national dataset

In [ ]:
df[df["state"]==48.0] #grabbing Texas data from national dataset

,STATEFP10,COUNTYFP10,COUNTYNS10,GEOID10,NAME10,NAMELSAD10,LSAD10,CLASSFP10,MTFCC10,CSAFP10,...,ssp42095,ssp52095,ssp12100,ssp22100,ssp32100,ssp42100,ssp52100,race,state,county
10,48,113,1383842,48113,Dallas,Dallas County,6,H1,G4020,206.0,...,459465.564941,900451.752197,547147.789185,564916.803528,327880.469788,430352.187744,891243.733215,1,48.0,113.0
11,48,227,1383899,48227,Howard,Howard County,6,H1,G4020,NaN,...,15667.139221,30040.063950,18433.054779,19134.407696,11252.495304,14661.397850,29800.315147,1,48.0,227.0
12,48,155,1383863,48155,Foard,Foard County,6,H1,G4020,NaN,...,71.250100,117.946046,73.395594,72.527873,44.134315,61.290130,104.364300,1,48.0,155.0
13,48,153,1383862,48153,Floyd,Floyd County,6,H1,G4020,NaN,...,51.172177,77.915650,49.924458,47.836228,29.750669,42.227981,66.035550,1,48.0,153.0
14,48,43,1383807,48043,Brewster,Brewster County,6,H1,G4020,NaN,...,860.107912,1554.167811,923.153924,945.479642,566.756257,751.998846,1430.515445,1,48.0,43.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2994,48,297,1383934,48297,Live Oak,Live Oak County,6,H1,G4020,NaN,...,5554.060452,10605.843445,6701.133667,6936.298080,4080.816673,5357.685104,10762.795303,1,48.0,297.0
2995,48,345,1383958,48345,Motley,Motley County,6,H1,G4020,NaN,...,75.930179,129.747672,76.863550,77.016216,47.366398,63.449258,112.815383,1,48.0,345.0
2996,48,421,1383996,48421,Sherman,Sherman County,6,H1,G4020,NaN,...,544.758346,1020.792784,619.024272,632.907923,373.413592,496.060960,975.147216,1,48.0,421.0
2997,48,357,1383964,48357,Ochiltree,Ochiltree County,6,H1,G4020,NaN,...,1318.357276,2487.180472,1451.854949,1499.796624,886.679143,1163.704978,2318.362521,1,48.0,357.0
2998,48,91,1383831,48091,Comal,Comal County,6,H1,G4020,NaN,...,215351.434082,387667.060059,271989.405518,263178.439453,151842.600586,214293.559326,401388.217773,1,48.0,91.0